// Package cartofacade contains the api to call into CGO
//
//nolint:lll
package cartofacade

/*
	#cgo CFLAGS: -I../viam-cartographer/src/carto_facade

	// the libraries that need to be linked can be derived from line 258 of the build.ninja file that is autogenerated during make build
  #cgo LDFLAGS: -L../viam-cartographer/build -L../viam-cartographer/build/cartographer -lviam-cartographer  -lcartographer -ldl -lm -labsl_hash  -labsl_city -labsl_bad_optional_access -labsl_strerror  -labsl_str_format_internal -labsl_synchronization -labsl_strings -labsl_throw_delegate -lcairo -llua5.3 -lstdc++ -lceres -lprotobuf -lglog -lboost_filesystem -lboost_iostreams -lpcl_io -lpcl_common -labsl_raw_hash_set


  #include "../viam-cartographer/src/carto_facade/carto_facade.h"

  int sum(int a, int b) {
	  return a + b;
  }
*/
import "C"

// Hi is a mistake
func Hi() int {
	a := 1
	return int(C.sum(C.int(a), C.int(a)))
}
